on:
 schedule:
   - cron: "0 2 * * *"

name: Merced weather update

jobs:
  render:
    name: Update graphs
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          # don't reinstall R
          install-r: false
          # use RStudio's CRAN mirror with precompiled binaries
          use-public-rspm: true
      - name: Cache packages
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
      - name: Retrieve data
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 30
          max_attempts: 3
          command: Rscript -e 'source("R/Retrieve_GHCN_USC00045532_USW00023257.R")'
          continue_on_error: true
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data
      - name: Build graph
        run:  Rscript -e 'source("R/BuildDailyHigh.R")'
      - name: Commit graph
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update graph
